# Generated by Django 5.0.4 on 2024-05-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GondolaShelving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.CharField(choices=[('island', 'Island/Gondola (double-sided)'), ('wall', 'Wall (single-sided)')], max_length=6)),
                ('color', models.CharField(choices=[('CHR', 'Chrome'), ('PLT', 'Platinum')], max_length=3)),
                ('side_a_back_panel_type', models.CharField(choices=[('pegboard', 'Pegboard'), ('solid', 'Solid')], max_length=8)),
                ('side_b_back_panel_type', models.CharField(choices=[('pegboard', 'Pegboard'), ('solid', 'Solid')], max_length=8)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('side_a_base_depth', models.IntegerField()),
                ('side_b_base_depth', models.IntegerField()),
                ('upper_shelves_quantity_per_section', models.IntegerField(default=0)),
                ('upper_shelf_type', models.CharField(choices=[('TL', 'Tilt-in'), ('DL', 'Drop-in')], max_length=2)),
                ('upper_shelf_depth', models.IntegerField()),
                ('base_height', models.CharField(max_length=2)),
                ('wall_mount_qty', models.CharField(max_length=15)),
            ],
        ),
    ]
