# Generated by Django 5.0.4 on 2024-05-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_gondolashelving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gondolashelving',
            name='wall_mount_qty',
        ),
    ]
