# Generated by Django 5.0.4 on 2024-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_gondolashelving_side_a_base_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gondolashelving',
            name='base_height',
            field=models.CharField(choices=[('06', '6 inches'), ('LB', 'Low Base')], default='06', max_length=2),
        ),
        migrations.AlterField(
            model_name='gondolashelving',
            name='color',
            field=models.CharField(choices=[('CHR', 'Chrome'), ('PLT', 'Platinum')], default='CHR', max_length=3),
        ),
        migrations.AlterField(
            model_name='gondolashelving',
            name='configuration',
            field=models.CharField(choices=[('island', 'Island/Gondola (double-sided)'), ('wall', 'Wall (single-sided)')], default='island', max_length=10),
        ),
        migrations.AlterField(
            model_name='gondolashelving',
            name='height',
            field=models.CharField(choices=[('48', '48 inches'), ('54', '54 inches'), ('60', '60 inches'), ('66', '66 inches'), ('72', '72 inches'), ('78', '78 inches'), ('84', '84 inches'), ('90', '90 inches'), ('96', '96 inches')], default='48', max_length=3),
        ),
        migrations.AlterField(
            model_name='gondolashelving',
            name='side_a_base_width',
            field=models.CharField(choices=[('13', '13 inches'), ('16', '16 inches'), ('19', '19 inches'), ('22', '22 inches'), ('25', '25 inches'), ('28', '28 inches'), ('31', '31 inches')], default='13', max_length=3),
        ),
        migrations.AlterField(
            model_name='gondolashelving',
            name='side_b_base_width',
            field=models.CharField(choices=[('13', '13 inches'), ('16', '16 inches'), ('19', '19 inches'), ('22', '22 inches'), ('25', '25 inches'), ('28', '28 inches'), ('31', '31 inches')], default='13', max_length=3),
        ),
        migrations.AlterField(
            model_name='gondolashelving',
            name='upper_shelf_depth',
            field=models.CharField(choices=[('13', '13 inches'), ('16', '16 inches'), ('19', '19 inches'), ('22', '22 inches'), ('25', '25 inches'), ('28', '28 inches'), ('31', '31 inches')], default='13', max_length=3),
        ),
    ]
