# Generated by Django 5.0.4 on 2024-05-09 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_gondolashelving_base_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gondolashelving',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
